// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCalendar() {
  return window['go']['main']['App']['GetCalendar']();
}

export function OffsetCalendar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OffsetCalendar'](arg1, arg2, arg3, arg4);
}

export function SetCalendar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCalendar'](arg1, arg2, arg3);
}
